import type { Metadata } from "next";
import "./globals.css";
import fonts from "@/fonts";
import { ReactNode } from "react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${fonts.inter.variable}
        ${fonts.anton.variable}
        ${fonts.arima.variable}
        text-primary-blue 
      `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
